name: Set Community Variables

on:
  workflow_call:
    outputs:
      kind_version:
        description: 'KinD version to set up'
        value: ${{ jobs.set_variables.outputs.kind_version }}

jobs:
  set_variables:
    runs-on: ubuntu-latest
    outputs:
      kind_version: '0.20.0'
    steps:
      - id: set_variables
        run: |
          echo "Set Community Variables"
