name: Community KinD

on:
  pull_request:
    branches:
      - main
      - arybolovlev:main

jobs:
  set_variables:
    uses: ./.github/workflows/reusable-community-variables.yaml
  set_up_kind:
    uses: ./.github/workflows/reusable-kind.yaml
    needs: [set_variables]
    with:
      kind_version: ${{ needs.set_variables.outputs.kind_versions }}
