name: kind

on:
  schedule:
    - cron: '25 * * * *'
  workflow_dispatch:
    inputs:
      kind_version:
        description: 'The kind version.'
        default: 0.17.0

env:
  KIND_VERSION: ${{ github.event.inputs.kind_version || vars.KIND_VERSION }}

jobs:
  set-up-kind:
    runs-on: ubuntu-latest
    steps:
      - name: Print the kind version
        run: |
          echo v${{ env.KIND_VERSION }}
      - name: Set up kind
        uses: helm/kind-action@dda0770415bac9fc20092cacbc54aa298604d140 # v1.8.0
        with:
          wait: 2m
          version: v${{ env.KIND_VERSION }}
