name: kind

on:
  schedule:
    - cron: '25 * * * *'
  pull_request:
    branches:
      - main
      - arybolovlev:main
  workflow_dispatch:
    inputs:
      kind_version:
        description: 'The kind version.'
        default: 0.17.0

env:
  KIND_VERSION: ${{ github.event.inputs.kind_version || vars.KIND_VERSION }}

jobs:
  set-up-env-variables:
    permissions: write-all
    #  actions: write
    runs-on: ubuntu-latest
    steps:
      - name: Set the KinD version
        env:
          KIND_VERSION: ${{ vars.KIND_VERSION }}
        run: |
          echo v${{ env.KIND_VERSION }}
  set-up-kind:
    runs-on: ubuntu-latest
    needs: [set-up-env-variables]
    steps:
      - name: Print the KinD version
        run: |
          echo v${{ env.KIND_VERSION }}
      - name: Set up kind
        uses: helm/kind-action@dda0770415bac9fc20092cacbc54aa298604d140 # v1.8.0
        with:
          wait: 2m
          version: v${{ env.KIND_VERSION }}
