name: kind

on:
  schedule:
    - cron: '25 * * * *'
  pull_request:
    branches:
      - main
      - arybolovlev:main
  workflow_dispatch:
    inputs:
      kind_version:
        description: 'The kind version.'
        default: 0.17.0

# env:
#   KIND_VERSION: ${{ github.event.inputs.kind_version || '0.20.0' }}

permissions: write-all

jobs:
  set_env_variables:
    uses: ./.github/workflows/community-variables.yaml
  set_up_kind:
    runs-on: ubuntu-latest
    needs: [set_env_variables]
    steps:
      - env:
          KIND_VERSION: ${{ needs.set_env_variables.outputs.kind_version }}
      - name: Print the KinD version
        run: |
          echo v${{ env.KIND_VERSION }}
      - name: Set up kind
        uses: helm/kind-action@dda0770415bac9fc20092cacbc54aa298604d140 # v1.8.0
        with:
          wait: 2m
          version: v${{ env.KIND_VERSION }}
