name: On

on:
  pull_request:
    branches:
      - 'release/v*'
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  on:
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: |
          echo "Hello!"
      - name: skopeo
        run: |
          skopeo --version
          TAG=`skopeo list-tags docker://docker.io/kindest/node | jq '.Tags.[]' | sort -nr | grep -m1 1.29 | tr -d '"'` curl -s https://hub.docker.com/v2/namespaces/kindest/repositories/node/tags/$TAG | jq '.digest'
