name: Parallel

on:
  workflow_dispatch:

jobs:
  on:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Number of CPUs
        run: |
          go run main.go
