name: Parallel

on:
  workflow_dispatch:

jobs:
  on:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
      - name: Number of CPUs
        run: |
          go run main.go
