name: Parallel

on:
  workflow_dispatch:

jobs:
  on:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      - name: Number of CPUs
        run: |
          go run main.go
