name: Parallel

on:
  workflow_dispatch:

jobs:
  on:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - name: Number of CPUs
        run: |
          go run main.go
