name: Reusable set up KinD

on:
  workflow_call:
    inputs:
      kind_version:
        required: true
        type: string

jobs:
  reusable_set_up_kind:
    runs-on: ubuntu-latest
    env:
      KIND_VERSION: ${{ inputs.kind_version }}
    steps:
      - name: Set up KinD
        uses: helm/kind-action@dda0770415bac9fc20092cacbc54aa298604d140 # v1.8.0
        with:
          wait: 2m
          version: v${{ env.KIND_VERSION }}
