name: Reusable Variables

on:
  workflow_call:
    outputs:
      kind_version:
        description: 'KinD version to set up'
        value: ${{ jobs.reusable_variables.outputs.kind_version }}

jobs:
  reusable_variables:
    runs-on: ubuntu-latest
    outputs:
      kind_version: '0.20.0'
    steps:
      - name: Set variables
        run: |
          echo "Set variables"
