name: Terraform

on:
  workflow_dispatch:

env:
  TERRAFORM_VERSION: '1.5.4'

jobs:
  terraform:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Install Terraform
        uses: hashicorp/setup-terraform@a1502cd9e758c50496cc9ac5308c4843bcd56d36 # v3.0.0
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}
          terraform_wrapper: false
      - name: Find Terraform
        run: |
          echo ${{ runner.temp }}
          whereis terraform
          whereis -B ${{ runner.temp }}/* -f terraform
          echo "TF_ACC_TERRAFORM_PATH=`whereis -B ${{ runner.temp }}/* -f terraform | awk '{print $2}'`" >> "$GITHUB_ENV"
          terraform --version
      - name: Print Path
        run: |
          echo $TF_ACC_TERRAFORM_PATH
